version: '3.1'
services:
    db:
        image: postgres:alpine
        restart: "no"
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_USER: user
        ports:
            - 5432:5432
