version: '2.0'
services:
    db:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_USER: user
        ports:
            - 5432:5432
    backend:
        build: .
        environment:
            FLASK_APP: /var/www/app/src/main.py
            FLASK_DEBUG: 1
        volumes:
            - ./app:/var/www/app
        ports:
            - "5000:5000"

    nginx:
        build: nginx
        volumes:
            - ./app/static:/usr/share/nginx/html
        ports:
            - 80:80
