version: '2.0'
services:
    backend:
        build: ./app/backend/
        environment:
            FLASK_APP: /var/www/app/src/main.py
            FLASK_DEBUG: 1
        env_file:
            - ./secrets.env
        volumes:
            - ./app/backend/:/var/www/app
        ports:
            - "5000:5000"

    frontend:
        build: ./app/frontend
        ports:
            - 80:80
